### ISSUE TITLE
Property Names with hyphens

### ISSUE THREAD

**Issue by ghost** [MarketSquare/robotframework-openapidriver#32]
Property names in the OpenAPI spec file that contain hyphens throw a TypeError.

TypeError: Field names must be valid identifiers: 'device-data'

Is it possible to address this?

**Comment by robinmackaij** [comment]
Thanks for the report. I'll take a look after my holidays. A stack trace with the line number where the exception occurs would be helpful.

Without the code at hand, I would guess the issue is that kebab-case is not allowed in names of functions and variables (and properties are methods / functions) in Python. I think the solution will be to convert kebab-case property names to snake_case.

JSON naming convention is camelCase for properties, so you may want to consider that in your property naming scheme.
________________________________
From: TerryMcCabe-EN0038 ***@***.***>
Sent: Thursday, July 20, 2023 7:22:14 PM
To: MarketSquare/robotframework-openapidriver ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [MarketSquare/robotframework-openapidriver] Property Names with hyphens (Issue #32)


Property names in the OpenAPI spec file that contain hyphens throw a TypeError.

TypeError: Field names must be valid identifiers: 'device-data'

Is it possible to address this?

**Comment by ghost** [comment]
Thank you @robinmackaij !

Unfortunately the naming scheme is out of my control, this is a sample of property names in the spec:

`- user-type`

The Dev team have used this quite extensively :-(

Your library looks like it would be of great value if I could overcome this!

Stack Trace:


FAIL | TypeError: Field names must be valid identifiers: 'device-data' |  

DEBUG | Traceback (most recent call last):
  File "../lib/python3.9/site-packages/OpenApiDriver/openapi_executors.py", line 170, in test_endpoint
    request_data: RequestData = self.get_request_data(method=method, endpoint=path)
  File ../lib/python3.9/site-packages/OpenApiLibCore/openapi_libcore.py", line 821, in get_request_data
    dto_class = make_dataclass(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/dataclasses.py", line 1219, in make_dataclass
    raise TypeError(f'Field names must be valid identifiers: {name!r}')
TypeError: Field names must be valid identifiers: 'device-data'

**Comment by ghost** [comment]
@robinmackaij thank you for the quick turnaround on this.

I have upgraded and tested and all looks good and I am continuing to experiment with your library with this fix.
