### ISSUE TITLE
Ability to set origin after library is loaded

### ISSUE THREAD

**Issue by dalybrown** [MarketSquare/robotframework-openapidriver#38]
I couldn't find this in the documentation anywhere, but I'm wondering if we can set the origin server after loading the library. 

I wanted to use this library to test my API but the problem I have is my robot tests also start the server and I don't know the hostname ahead of time. I tried to import the library later on in a keyword using the `Import Library` builtin keyword. However, that didn't seem to be able to generate any tests.

I think to address this issue, it would be nice to support:

- Setting the origin server after the library is imported; or
- Support the `Import Library` keyword so we can delay importing the library.

For now, I can add a temporary hosts entry or something like that to work around it (unless the library supports setting the origin after importing it and I just didn't find it!).

Thanks!

~Update: I guess there is an even simpler solution :). I can literally modify the path myself in the test template. You can ignore this issue then or maybe it's still relevant!~ (that update doesn't work :()

**Comment by robinmackaij** [comment]
At what point in time do you know the hostname? Is the server started in another test suite or in the same suite in a `Suite Setup`?

I can think of some options, but much depends on exactly when / how the server is started.

**Comment by dalybrown** [comment]
It is started in the same test suite during setup (usually). I tried the `Import Library` keyword after starting it but that doesn't seem to generate the tests.

I currently workaround it by temporarily adding an entry to `/etc/hosts`. It works fine for now, but it would be nice not to have to modify that file.

**Comment by robinmackaij** [comment]
What you could perhaps try is running the code to start the server from a Python variables file and import that before importing the library.

What the variables file would do is start the server, get it's hostname and return that as a variable.

**Comment by dalybrown** [comment]
Thanks for the response. I prefer the way I currently start the server within robot, because it does some checks in addition to that. My workaround using the hosts file is fine for now.

Out of curiosity, is there a reason the origin server must be specified when importing the library (and can't be set afterwards via a keyword or something)?

**Comment by robinmackaij** [comment]
> Out of curiosity, is there a reason the origin server must be specified when importing the library (and can't be set afterwards via a keyword or something)?

Initially (before this was opensourced) the library accepted only a single url; the url to where the OAS file is hosted. The hostname would be derived from that. Back then, OpenApiLibCore was not extracted yet.

After the library was opensourced and I used it on another project, the spec location and target host were uncoupled to allow using the library to work for situations where the OAS is not available on the server (not every servers gives public access to the OAS / Swagger UI) or where the OAS needs to be manually tweaked to work properly with the library (especially when the OAS gets created manually instead of generated by a framework, standards get violated).

The situation where the target hostname is not yet known when running the suite of which OpenApiDriver / OpenApiLibCore is a part is a situation that you're the first to bring up, so "delayed" setting of the target host is a new request / scenario. Now for OpenApiLibCore, adding a keyword to change the target host should be simple. Whether that is also the case for OpenApiDriver is something I'd need to investigate. Perhaps just exposing that keyword and calling it during Suite Setup would work, but DataDriver is also doing it's magic, so I'd need to actually implement this and try it out.

I'm definitely willing to investigate / implement this, but currently I won't have the time for that the coming 2 weeks. It's also something that I'd rather do in the repo where I'll be bringing OpenApiDriver and OpenApiLibCore together into a single repo again (in hindsight, extracting OpenApiLibCore into a separate repo wasn't the best choice). This is due to supporting this will change the interface of both libraries, meaning 2 (linked) releases in the current situation.

**Comment by dalybrown** [comment]
Thanks for the explanation!

I'm not in a rush; I also understand the time constraints regarding working on open source projects!

I'm happy to help implement it if you want; however, I'm in the same boat in that it wouldn't be for a month or two!

**Comment by robinmackaij** [comment]
@dalybrown After a refactor to make the library work more nicely with a language server, it was trivial to implement a `Set Origin`. I have that working in the repo where I'm bringing OpenApiDriver and OpenApiLibCore together.

What's important to note though is that this only works for the `origin` and not for the `source`; the location of the openapi.json / openapi.yaml must be known / available at moment the library is imported.

This is due to the nature of how DataDriver works; what DataDriver does is that it removes all test cases from a suite and then adds the test cases it gets from the data source to the (empty) suite. In case of OpenApiDriver, the data source is the content of the openapi.json / openapi.yaml. This happens before that suite content is finalized and thus before the `Suite Setup` is executed. Note that the `Suite Setup` is the first moment in test execution where keywords can be called.

**Comment by dalybrown** [comment]
Awesome - that will work for us!

**Comment by robinmackaij** [comment]
> Awesome - that will work for us!

I've implemented this in https://pypi.org/project/robotframework-openapitools/
This is a drop-in replacement for OpenApiDriver and OpenApiLibCore. Could you give it a try?

**Comment by dalybrown** [comment]
Awesome! I'm away until the 25th of March so when I'm back I will give it a shot (small chance I can try it out today or tomorrow though, I will report back if I do). Thanks for updating!

**Comment by dalybrown** [comment]
Took me a few extra weeks but I finally tried it out. Works great - thanks!
