### ISSUE TITLE
inconsistent behaviour with Validate Response keyword

### ISSUE THREAD

**Issue by dalybrown** [MarketSquare/robotframework-openapidriver#40]
I'm not sure if this is an error on my part or the library. I am having inconsistent results with the `Validate Response` keyword when running locally on my machine and when running in a CI environment (we use GitLab CI).

Locally my tests run fine with this library. When run in a pipeline, they fail on the `Validate Response` keyword. The error I get is:

```
AttributeError: 'NoneType' object has no attribute 'errors'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/OpenApiDriver/openapi_executors.py", line 387, in validate_response
    self._validate_response_against_spec(response)
  File "/usr/local/lib/python3.11/dist-packages/OpenApiDriver/openapi_executors.py", line 490, in _validate_response_against_spec
    for error in validation_result.errors:
                 ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'errors'
```

If I use another library to check the API, like the RequestsLibrary, it works fine both locally and in our pipelines: my server that I'm testing responds to the command like I expect.

I am having difficulty figuring out what this error message is trying to tell me (besides the obvious AttributeError`). There is a *slight* difference in the setup when running at my desk and in our CI environment. Presumably that is what is causing the issue, but I can't figure out why or where (since, again, using another library to test the API works fine). The server seemingly is responding to the request using this library.

Thanks!

**Comment by robinmackaij** [comment]
To support Python 3.12, I had to update a number of downstream dependencies. The package I use for the validation was  changed and the above code no longer applies. Could you upgrade OpenApiDriver / OpenApiLibCore on the machine where you got this error?

Please note that typically, you won't get any errors like this when using libraries like RequestsLibrary or tools like Postman; this issue is a problem in a package that validates the response received against that OAS. Other libraries / tools typically don't perform any validations like that; they'll just return whatever the server returned to you, even if that validates the OAS.

**Comment by dalybrown** [comment]
Thanks for the response! We are using `4.2.1` so I'll update to `4.3.0` and try it out.

It's the same instance on both machines: everything is containerized and it is the same image. The only difference is the pipelines have a builtin DNS server whereas at my desk I add an entry to the hosts file.

With the new code, is there a way to be more verbose regarding what isn't validating properly?

**Comment by dalybrown** [comment]
Updating fixed the issue. Awesome - thanks!
